# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cukunity"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mario Freitas"]
  s.date = "2013-08-08"
  s.description = "cukunity is a tool inspired by the principles of Behaviour Driven Development. Cukunity is a portmanteau of \"Cucumber\" and \"Unity\", and as so it provides helpers to play nicely with cucumber, although it can be used standalone for automation. "
  s.email = "imkira@gmail.com"
  s.executables = ["cukunity"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README_JA.md"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README_JA.md",
    "Rakefile",
    "Unity/Assets/Demo.meta",
    "Unity/Assets/Demo/Art.meta",
    "Unity/Assets/Demo/Art/Buttons.meta",
    "Unity/Assets/Demo/Art/Buttons/down.png",
    "Unity/Assets/Demo/Art/Buttons/down.png.meta",
    "Unity/Assets/Demo/Art/Buttons/left.png",
    "Unity/Assets/Demo/Art/Buttons/left.png.meta",
    "Unity/Assets/Demo/Art/Buttons/ok.png",
    "Unity/Assets/Demo/Art/Buttons/ok.png.meta",
    "Unity/Assets/Demo/Art/Buttons/options.png",
    "Unity/Assets/Demo/Art/Buttons/options.png.meta",
    "Unity/Assets/Demo/Art/Buttons/play.png",
    "Unity/Assets/Demo/Art/Buttons/play.png.meta",
    "Unity/Assets/Demo/Art/Buttons/quit.png",
    "Unity/Assets/Demo/Art/Buttons/quit.png.meta",
    "Unity/Assets/Demo/Art/Buttons/retry.png",
    "Unity/Assets/Demo/Art/Buttons/retry.png.meta",
    "Unity/Assets/Demo/Art/Buttons/right.png",
    "Unity/Assets/Demo/Art/Buttons/right.png.meta",
    "Unity/Assets/Demo/Art/Buttons/up.png",
    "Unity/Assets/Demo/Art/Buttons/up.png.meta",
    "Unity/Assets/Demo/Art/clear.png",
    "Unity/Assets/Demo/Art/clear.png.meta",
    "Unity/Assets/Demo/Art/options.png",
    "Unity/Assets/Demo/Art/options.png.meta",
    "Unity/Assets/Demo/Art/sokoban.png",
    "Unity/Assets/Demo/Art/sokoban.png.meta",
    "Unity/Assets/Demo/Cubes.meta",
    "Unity/Assets/Demo/Cubes/CrateCube.mat",
    "Unity/Assets/Demo/Cubes/CrateCube.mat.meta",
    "Unity/Assets/Demo/Cubes/CrateCube.prefab",
    "Unity/Assets/Demo/Cubes/CrateCube.prefab.meta",
    "Unity/Assets/Demo/Cubes/FloorCube.mat",
    "Unity/Assets/Demo/Cubes/FloorCube.mat.meta",
    "Unity/Assets/Demo/Cubes/FloorCube.prefab",
    "Unity/Assets/Demo/Cubes/FloorCube.prefab.meta",
    "Unity/Assets/Demo/Cubes/GoalCube.mat",
    "Unity/Assets/Demo/Cubes/GoalCube.mat.meta",
    "Unity/Assets/Demo/Cubes/GoalCube.prefab",
    "Unity/Assets/Demo/Cubes/GoalCube.prefab.meta",
    "Unity/Assets/Demo/Cubes/PlayerCube.mat",
    "Unity/Assets/Demo/Cubes/PlayerCube.mat.meta",
    "Unity/Assets/Demo/Cubes/PlayerCube.prefab",
    "Unity/Assets/Demo/Cubes/PlayerCube.prefab.meta",
    "Unity/Assets/Demo/Cubes/WallCube.mat",
    "Unity/Assets/Demo/Cubes/WallCube.mat.meta",
    "Unity/Assets/Demo/Cubes/WallCube.prefab",
    "Unity/Assets/Demo/Cubes/WallCube.prefab.meta",
    "Unity/Assets/Demo/Resources.meta",
    "Unity/Assets/Demo/Resources/MainMenu.prefab",
    "Unity/Assets/Demo/Resources/MainMenu.prefab.meta",
    "Unity/Assets/Demo/Resources/OptionsMenu.prefab",
    "Unity/Assets/Demo/Resources/OptionsMenu.prefab.meta",
    "Unity/Assets/Demo/Scripts.meta",
    "Unity/Assets/Demo/Scripts/CameraController.js",
    "Unity/Assets/Demo/Scripts/CameraController.js.meta",
    "Unity/Assets/Demo/Scripts/EnterPlayerName.js",
    "Unity/Assets/Demo/Scripts/EnterPlayerName.js.meta",
    "Unity/Assets/Demo/Scripts/GameLeftButton.js",
    "Unity/Assets/Demo/Scripts/GameLeftButton.js.meta",
    "Unity/Assets/Demo/Scripts/GameQuitButton.js",
    "Unity/Assets/Demo/Scripts/GameQuitButton.js.meta",
    "Unity/Assets/Demo/Scripts/GameRetryButton.js",
    "Unity/Assets/Demo/Scripts/GameRetryButton.js.meta",
    "Unity/Assets/Demo/Scripts/GameRightButton.js",
    "Unity/Assets/Demo/Scripts/GameRightButton.js.meta",
    "Unity/Assets/Demo/Scripts/GameUpButton.js",
    "Unity/Assets/Demo/Scripts/GameUpButton.js.meta",
    "Unity/Assets/Demo/Scripts/OnTouchGUIElementDown.js",
    "Unity/Assets/Demo/Scripts/OnTouchGUIElementDown.js.meta",
    "Unity/Assets/Demo/Scripts/PlayerData.js",
    "Unity/Assets/Demo/Scripts/PlayerData.js.meta",
    "Unity/Assets/Demo/Scripts/SokobanController.js",
    "Unity/Assets/Demo/Scripts/SokobanController.js.meta",
    "Unity/Assets/Demo/Scripts/TakeScreenShot.js",
    "Unity/Assets/Demo/Scripts/TakeScreenShot.js.meta",
    "Unity/Assets/Demo/Scripts/TitleOptionsButton.js",
    "Unity/Assets/Demo/Scripts/TitleOptionsButton.js.meta",
    "Unity/Assets/Demo/Scripts/TitleOptionsOkButton.js",
    "Unity/Assets/Demo/Scripts/TitleOptionsOkButton.js.meta",
    "Unity/Assets/Demo/Scripts/TitlePlayButton.js",
    "Unity/Assets/Demo/Scripts/TitlePlayButton.js.meta",
    "Unity/Assets/Demo/Scripts/TitleQuitButton.js",
    "Unity/Assets/Demo/Scripts/TitleQuitButton.js.meta",
    "Unity/Assets/Demo/Scripts/UpdateMovesLabel.js",
    "Unity/Assets/Demo/Scripts/UpdateMovesLabel.js.meta",
    "Unity/Assets/Demo/Scripts/UpdatePlayerName.js",
    "Unity/Assets/Demo/Scripts/UpdatePlayerName.js.meta",
    "Unity/Assets/Demo/demo_game.unity",
    "Unity/Assets/Demo/demo_game.unity.meta",
    "Unity/Assets/Demo/demo_title.unity",
    "Unity/Assets/Demo/demo_title.unity.meta",
    "Unity/Assets/Plugins.meta",
    "Unity/Assets/Plugins/CukunityInstance.prefab",
    "Unity/Assets/Plugins/CukunityInstance.prefab.meta",
    "Unity/Assets/Plugins/CukunityServer.cs",
    "Unity/Assets/Plugins/CukunityServer.cs.meta",
    "Unity/Assets/Plugins/JsonFx.Json.dll",
    "Unity/Assets/Plugins/JsonFx.Json.dll.meta",
    "Unity/Assets/Plugins/iOS.meta",
    "Unity/Assets/Plugins/iOS/CukunityServer.mm",
    "Unity/Assets/Plugins/iOS/CukunityServer.mm.meta",
    "Unity/Library/AudioManager.asset",
    "Unity/Library/BuildSettings.asset",
    "Unity/Library/DynamicsManager.asset",
    "Unity/Library/EditorBuildSettings.asset",
    "Unity/Library/EditorSettings.asset",
    "Unity/Library/EditorUserBuildSettings.asset",
    "Unity/Library/EditorUserSettings.asset",
    "Unity/Library/InputManager.asset",
    "Unity/Library/InspectorExpandedItems.asset",
    "Unity/Library/MonoManager.asset",
    "Unity/Library/NetworkManager.asset",
    "Unity/Library/ProjectSettings.asset",
    "Unity/Library/QualitySettings.asset",
    "Unity/Library/TagManager.asset",
    "Unity/Library/TimeManager.asset",
    "Unity/ProjectSettings/AudioManager.asset",
    "Unity/ProjectSettings/DynamicsManager.asset",
    "Unity/ProjectSettings/EditorBuildSettings.asset",
    "Unity/ProjectSettings/EditorSettings.asset",
    "Unity/ProjectSettings/InputManager.asset",
    "Unity/ProjectSettings/NavMeshLayers.asset",
    "Unity/ProjectSettings/NetworkManager.asset",
    "Unity/ProjectSettings/ProjectSettings.asset",
    "Unity/ProjectSettings/QualitySettings.asset",
    "Unity/ProjectSettings/TagManager.asset",
    "Unity/ProjectSettings/TimeManager.asset",
    "VERSION",
    "bin/cukunity",
    "cukunity.gemspec",
    "features/get_scene_command.feature",
    "features/i18n/ja/sokoban_clear.feature",
    "features/install.feature",
    "features/keyboard_input.feature",
    "features/load_level_command.feature",
    "features/run.feature",
    "features/select_visible.feature",
    "features/support/env.rb",
    "features/touch_input.feature",
    "lib/cukunity.rb",
    "lib/cukunity/cli.rb",
    "lib/cukunity/cli/argument_parser.rb",
    "lib/cukunity/cli/bootstrap_command.rb",
    "lib/cukunity/cli/doctor_command.rb",
    "lib/cukunity/cli/features_command.rb",
    "lib/cukunity/cli/main.rb",
    "lib/cukunity/cli/options.rb",
    "lib/cukunity/cucumber.rb",
    "lib/cukunity/cucumber/step_definitions/get_scene_command_steps.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja/get_scene_command_steps.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja/install_steps.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja/keyboard_input_steps.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja/load_level_command_steps.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja/run_steps.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja/select_visible_steps.rb",
    "lib/cukunity/cucumber/step_definitions/i18n/ja/touch_input_steps.rb",
    "lib/cukunity/cucumber/step_definitions/install_steps.rb",
    "lib/cukunity/cucumber/step_definitions/keyboard_input_steps.rb",
    "lib/cukunity/cucumber/step_definitions/load_level_command_steps.rb",
    "lib/cukunity/cucumber/step_definitions/run_steps.rb",
    "lib/cukunity/cucumber/step_definitions/select_visible_steps.rb",
    "lib/cukunity/cucumber/step_definitions/touch_input_steps.rb",
    "lib/cukunity/cucumber/support/platform_helpers.rb",
    "lib/cukunity/cucumber/support/spec_helpers.rb",
    "lib/cukunity/cucumber/support/transforms.rb",
    "lib/cukunity/cucumber/support/unity_helpers.rb",
    "lib/cukunity/drivers/android.rb",
    "lib/cukunity/drivers/android/app.rb",
    "lib/cukunity/drivers/android/appkiller/.gitignore",
    "lib/cukunity/drivers/android/appkiller/AndroidManifest.xml",
    "lib/cukunity/drivers/android/appkiller/ant.properties",
    "lib/cukunity/drivers/android/appkiller/build.xml",
    "lib/cukunity/drivers/android/appkiller/proguard.cfg",
    "lib/cukunity/drivers/android/appkiller/project.properties",
    "lib/cukunity/drivers/android/appkiller/res/layout/main.xml",
    "lib/cukunity/drivers/android/appkiller/res/values/strings.xml",
    "lib/cukunity/drivers/android/appkiller/src/cukunity/appkiller/AppKiller.java",
    "lib/cukunity/drivers/android/keyboard_input.rb",
    "lib/cukunity/drivers/android/keycodes.rb",
    "lib/cukunity/drivers/android/monkey_client.rb",
    "lib/cukunity/drivers/android/process.rb",
    "lib/cukunity/drivers/android/touch_input.rb",
    "lib/cukunity/drivers/android/tunnel_client_methods.rb",
    "lib/cukunity/drivers/android/unity_client.rb",
    "lib/cukunity/drivers/android/utils.rb",
    "lib/cukunity/drivers/iOS.rb",
    "lib/cukunity/drivers/iOS/app.rb",
    "lib/cukunity/drivers/iOS/keyboard_input.rb",
    "lib/cukunity/drivers/iOS/process.rb",
    "lib/cukunity/drivers/iOS/touch_input.rb",
    "lib/cukunity/drivers/iOS/tunnel_client_methods.rb",
    "lib/cukunity/drivers/iOS/uiautomation.rb",
    "lib/cukunity/drivers/iOS/uiautomation_master.rb",
    "lib/cukunity/drivers/iOS/uiautomation_slave.js",
    "lib/cukunity/drivers/iOS/uiautomation_slave.rb",
    "lib/cukunity/drivers/iOS/unity_client.rb",
    "lib/cukunity/drivers/iOS/utils.rb",
    "lib/cukunity/exceptions.rb",
    "lib/cukunity/keyboard_input_methods.rb",
    "lib/cukunity/request_line_response_client_methods.rb",
    "lib/cukunity/tasks/cucumber.rake",
    "lib/cukunity/touch_input_methods.rb",
    "lib/cukunity/unity.rb",
    "lib/cukunity/unity/client_methods.rb",
    "lib/cukunity/unity/command_facade.rb",
    "lib/cukunity/unity/component.rb",
    "lib/cukunity/unity/gameobject.rb",
    "lib/cukunity/unity/hint.rb",
    "lib/cukunity/unity/json_container.rb",
    "lib/cukunity/unity/level.rb",
    "lib/cukunity/unity/scene.rb",
    "lib/cukunity/unity/screen.rb",
    "lib/cukunity/unity/screen_hint_methods.rb",
    "lib/cukunity/unity/text_hint_methods.rb",
    "lib/cukunity/utils.rb"
  ]
  s.homepage = "http://github.com/imkira/cukunity"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.6"
  s.summary = "cukunity is an automation/testing framework that simplifies BDD testing of Unity 3D games."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 1.6.5"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 1.0.6"])
      s.add_runtime_dependency(%q<cucumber>, [">= 1.1.4"])
      s.add_runtime_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<yard>, "~> 0.9.20")
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.6"])
      s.add_development_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_development_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.6.5"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 1.0.6"])
    else
      s.add_dependency(%q<json>, [">= 1.6.5"])
      s.add_dependency(%q<term-ansicolor>, [">= 1.0.6"])
      s.add_dependency(%q<cucumber>, [">= 1.1.4"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<yard>, "~> 0.9.20")
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.6"])
      s.add_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_dependency(%q<json>, [">= 1.6.5"])
      s.add_dependency(%q<term-ansicolor>, [">= 1.0.6"])
    end
  else
    s.add_dependency(%q<json>, [">= 1.6.5"])
    s.add_dependency(%q<term-ansicolor>, [">= 1.0.6"])
    s.add_dependency(%q<cucumber>, [">= 1.1.4"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<yard>, "~> 0.9.20")
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.6"])
    s.add_dependency(%q<reek>, ["~> 1.2.8"])
    s.add_dependency(%q<roodi>, ["~> 2.1.0"])
    s.add_dependency(%q<json>, [">= 1.6.5"])
    s.add_dependency(%q<term-ansicolor>, [">= 1.0.6"])
  end
end

